### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by 347180440** [killerprojecte/Folia#9] opened 2023-08-01 08:10 UTC
### Stack trace

 [15:36:16 ERROR]: [io.papermc.paper.threadedregions.ThreadedRegionizer] Failed to acquire region ThreadedRegion{state=3,sectionCount=41,sections=[RegionSection{sectionCoordinate=[-19, -20],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1442844143},RegionSection{sectionCoordinate=[-21, -20],chunkCount=128,chunksBitset=00000000000000000000000000000000ffffffffffffffffffffffffffffffff,nonEmptyNeighbours=5,hash=858361924},RegionSection{sectionCoordinate=[-15, -21],chunkCount=5,chunksBitset=00020000000200c2000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=681883092},RegionSection{sectionCoordinate=[-20, -21],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1644449622},RegionSection{sectionCoordinate=[-15, -23],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1583297587},RegionSection{sectionCoordinate=[-19, -19],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=554382348},RegionSection{sectionCoordinate=[-23, -20],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1628695437},RegionSection{sectionCoordinate=[-17, -21],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=747384812},RegionSection{sectionCoordinate=[-21, -19],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1823652820},RegionSection{sectionCoordinate=[-19, -17],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1265366237},RegionSection{sectionCoordinate=[-20, -18],chunkCount=150,chunksBitset=03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff000003ff03ff03ff,nonEmptyNeighbours=3,hash=867701480},RegionSection{sectionCoordinate=[-17, -22],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=2122758204},RegionSection{sectionCoordinate=[-16, -23],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=127123491},RegionSection{sectionCoordinate=[-23, -21],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1181110684},RegionSection{sectionCoordinate=[-23, -19],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1328187408},RegionSection{sectionCoordinate=[-14, -22],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=332009744},RegionSection{sectionCoordinate=[-15, -20],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1620475603},RegionSection{sectionCoordinate=[-22, -18],chunkCount=195,chunksBitset=fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff80000fff8fff8fff8,nonEmptyNeighbours=3,hash=731544997},RegionSection{sectionCoordinate=[-21, -18],chunkCount=240,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffff0000ffffffffffff,nonEmptyNeighbours=5,hash=848372269},RegionSection{sectionCoordinate=[-20, -17],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1896937470},RegionSection{sectionCoordinate=[-22, -19],chunkCount=208,chunksBitset=fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8fff8,nonEmptyNeighbours=5,hash=572747753},RegionSection{sectionCoordinate=[-17, -20],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1512855901},RegionSection{sectionCoordinate=[-23, -18],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=605110471},RegionSection{sectionCoordinate=[-19, -18],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1628932223},RegionSection{sectionCoordinate=[-16, -20],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=399387812},RegionSection{sectionCoordinate=[-15, -22],chunkCount=5,chunksBitset=0000000000000000000000000000000000400008000000000062000000000000,nonEmptyNeighbours=3,hash=774591891},RegionSection{sectionCoordinate=[-16, -22],chunkCount=2,chunksBitset=0000000000000000000000000000000000010040000000000000000000000000,nonEmptyNeighbours=3,hash=376772538},RegionSection{sectionCoordinate=[-14, -23],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1274818939},RegionSection{sectionCoordinate=[-22, -21],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1821693958},RegionSection{sectionCoordinate=[-14, -21],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=758222764},RegionSection{sectionCoordinate=[-20, -20],chunkCount=80,chunksBitset=0000000000000000000000000000000003ff03ff03ff03ff03ff03ff03ff03ff,nonEmptyNeighbours=3,hash=1497550932},RegionSection{sectionCoordinate=[-21, -21],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1731515393},RegionSection{sectionCoordinate=[-22, -20],chunkCount=104,chunksBitset=00000000000000000000000000000000fff8fff8fff8fff8fff8fff8fff8fff8,nonEmptyNeighbours=3,hash=1298749045},RegionSection{sectionCoordinate=[-17, -23],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1812262043},RegionSection{sectionCoordinate=[-16, -21],chunkCount=14,chunksBitset=00000000000000000000b0000037203400200000040000000000000000000000,nonEmptyNeighbours=3,hash=596328767},RegionSection{sectionCoordinate=[-21, -17],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1650335123},RegionSection{sectionCoordinate=[-20, -19],chunkCount=160,chunksBitset=03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff03ff,nonEmptyNeighbours=5,hash=1694704979},RegionSection{sectionCoordinate=[-19, -21],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=782794076},RegionSection{sectionCoordinate=[-14, -20],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1473467151},RegionSection{sectionCoordinate=[-23, -17],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1694039223},RegionSection{sectionCoordinate=[-22, -17],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1165192931}]}
java.lang.NullPointerException: Cannot read field "connections" because the return value of "it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.get(long)" is null
        at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:148) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:66) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:244) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:795) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:627) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:957) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:362) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:36:16 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Uncaught exception in tick thread "Region Scheduler Thread #9"
java.lang.NullPointerException: Cannot read field "connections" because the return value of "it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.get(long)" is null
        at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:148) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:66) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:244) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:795) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:627) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:957) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:362) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"5625b94"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin and Datapack List

[16:06:36 INFO]: Server Plugins (60):
[16:06:36 INFO]: Bukkit Plugins:
[16:06:36 INFO]:  - ajLeaderboards, AntiCropTrampleFolia, argt, ArtMap, AtLite, Ball, BlockLocker, Cgifts, Chat2QQ
[16:06:36 INFO]:  ChatColor2, *ChatTPA, CoreProtect, cupbot, CustomJoinAndQuitMessages, DecentHolograms, DraconyxPro, *EasyCommand, Essentials, EssentialsSpawn
[16:06:36 INFO]:  EzChestShop, FartherViewDistance, FoliaFlow, *Ghome, GSit, HavenPack, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, Ip2region
[16:06:36 INFO]:  JukeboxExtendedReborn, LibsDisguises, LinearBot, LiteItemShow, *LiveRecorder, LuckPerms, MessageOverHead, MinesweeperMC, MiraiMC, Morphy
[16:06:36 INFO]:  PlaceholderAPI, Plan, PlayerGuild, PlayerTop, PlugMan, PowerBoard, ProtocolLib, RayTraceAntiXray, Skulls, SuperVanish
[16:06:36 INFO]:  TAB, ValorlessUtils, Vault, ViaBackwards, ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, Whitelist4QQ, WorldEdit

### Actions to reproduce (if known)

Unknown crashes about five times a day

### Folia version

[16:08:07 INFO]: This server is running DirtyFolia version git-DirtyFolia-"5625b94" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 5625b94 on ver/1.20)

**Comment by killerprojecte** [comment] 2023-08-01 12:50
Please test in original folia

I think this problem caused by folia not dirtyfolia/plugins

**Comment by 347180440** [comment] 2023-08-08 09:30
[17:03:57] [Region Scheduler Thread #4/INFO]: 091126 issued server command: /home
[17:04:01] [Region Scheduler Thread #1/INFO]: _KOSHINO_ issued server command: /home
[17:04:09] [Region Scheduler Thread #15/INFO]: RTY5419 was obliterated by a sonically-charged shriek
[17:04:13] [Region Scheduler Thread #7/INFO]: RTY5419 issued server command: /TP
[17:04:14] [Region Scheduler Thread #7/INFO]: Wang issued server command: /back
[17:04:19] [Region Scheduler Thread #9/INFO]: 091126 has made the advancement [Bee Our Guest]
[17:04:21] [Region Scheduler Thread #11/INFO]: RTY5419 issued server command: /tp Aderr6868
[17:04:31] [Region Scheduler Thread #1/INFO]: 091126 issued server command: /back
[17:04:33] [Region Scheduler Thread #0/INFO]: Asaki was obliterated by a sonically-charged shriek
[17:04:36] [Region Scheduler Thread #15/INFO]: Asaki issued server command: /tp RTY5419
[17:04:39] [User Authenticator #20/INFO]: UUID of player Farmalod is 3432c62d-7c81-3409-983c-704bf799d39e
[17:04:40] [Region Scheduler Thread #4/INFO]: Farmalod[/111.30.223.210:57853] logged in with entity id 510736 at ([world]-1317359.078387687, 34.0, -1169920.873515354)
[17:04:40] [Folia Async Scheduler Thread Timer - PowerBoard/WARN]: [PowerBoard] Could not read Farmalod's name color.The player's name will be white in the tablist.To avoid this, make sure, you have a valid colorcode at the end of your prefix.
[17:04:42] [Region Scheduler Thread #6/INFO]: Aderr6868 was obliterated by a sonically-charged shriek
[17:04:44] [Region Scheduler Thread #7/INFO]: Asaki was blown up by Aderr6868
[17:04:46] [Async Chat Thread - #86/INFO]: [Not Secure] [无公会]Asaki> ?
[17:04:47] [Region Scheduler Thread #5/INFO]: Asaki issued server command: /back
[17:04:49] [Region Scheduler Thread #14/INFO]: RTY5419 was slain by Warden
[17:04:51] [Region Scheduler Thread #7/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #18920 centered at chunk [7486, -12] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1672) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:367) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1048575 out of bounds for length 524289
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1297) ~[fastutil-8.5.9.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:249) ~[fastutil-8.5.9.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.put(Int2ObjectOpenHashMap.java:257) ~[fastutil-8.5.9.jar:?]
	at net.minecraft.server.level.ChunkTracker.addEntity(ChunkTracker.java:1079) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:706) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2780) ~[?:?]
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2717) ~[?:?]
	at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:282) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:195) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:323) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1265) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1340) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1551) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1529) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1482) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:913) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:63) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:422) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:771) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1650) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	... 6 more
[17:04:51] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[17:04:51] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[17:04:51] [Region shutdown thread/INFO]: Stopping server

**Comment by 347180440** [comment] 2023-08-08 09:44
[17:43:59 INFO]: Checking version, please wait...
[17:44:00 INFO]: This server is running DirtyFolia version git-DirtyFolia-"c4d50b6" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c4d50b6 on ver/1.20)
You are running the latest version
Previous version: git-DirtyFolia-"5625b94" (MC: 1.20.1)

**Comment by killerprojecte** [comment] 2023-08-09 00:09
> 

If you don't test the vanilla folia, I won't be able to locate the problem. This way the problem will never be resolved.

**Comment by 347180440** [comment] 2023-08-09 09:16
What should I do? I don't know English. Can I ask for guidance?

**Comment by killerprojecte** [comment] 2023-08-09 10:48
You need to check whether the problem is caused by PaperMC/Folia or a plugin. Currently DirtyFolia has not modified the code in this location, I think the probability of the problem caused by DirtyFolia is low. PS: My private server can run DirtyFolia normally and installed it  Never encountered a similar crash in the environment of 150+ plugins

Of course you can request Chinese support

**Comment by 347180440** [comment] 2023-08-11 13:02
[20:41:25 INFO]: shademan6666 issued server command: /back
[20:41:28 INFO]: Pinpe blew up
[20:41:31 INFO]: SundayJK issued server command: /back
[20:41:33 INFO]: Monster_LIU fell from a high place
[20:41:34 INFO]: Pinpe issued server command: /back
[20:41:40 INFO]: Monster_LIU issued server command: /back
[20:41:44 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #62806 centered at chunk [12039, 11974] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServaer.tickChildren(MinecraftServer.java:1672) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:367) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2097152 out of bounds for length 1048577
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.rehash(Int2ObjectOpenHashMap.java:1302) ~[fastutil-8.5.9.jar:?]
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.insert(Int2ObjectOpenHashMap.java:249) ~[fastutil-8.5.9.jar:?]
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap.put(Int2ObjectOpenHashMap.java:257) ~[fastutil-8.5.9.jar:?]
        at net.minecraft.server.level.ChunkTracker.addEntity(ChunkTracker.java:1079) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:706) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2780) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2717) ~[?:?]
        at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:282) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:195) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:323) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1265) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1340) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1551) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1529) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1482) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:913) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:63) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:422) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1650) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
        ... 6 more


https://s1.ax1x.com/2023/08/11/pPn4jbj.png



This is the player Monster_LIU who was building a large pigman tower during gameplay, but died from falling. After using the "/back" command to return, the server experienced an error and crashed.

**Comment by killerprojecte** [comment] 2023-08-11 18:31
May I ask which plugin you use to implement the /back command?

**Comment by 347180440** [comment] 2023-08-11 18:33
essentialsx

**Comment by killerprojecte** [comment] 2023-08-11 18:35
I think you should try using HuskHomes to replace /back feature

**Comment by killerprojecte** [comment] 2023-08-11 18:37
From the current point of view, the operation of entity movement in incompatible plugins may cause some problems.

**Comment by 347180440** [comment] 2023-08-11 18:38
#8 Regarding the issue from the previous post, I simply wrote a plugin myself. If a player is teleported there, they are immediately sent back to spawn, and then sent back again using the 'back' command. This way, the chunks load correctly. However, today, players are still falling down. So, I increased the teleport delay by 0.4 seconds. I've been observing this for the past few days, and it's been crashing every day.

**Comment by 347180440** [comment] 2023-08-11 18:39
If a player triggers this bug, the chunks won't load and they fall into the void. Any actions by the player are ineffective, and after quitting, they can't log back in. In the game, it still shows them as online. The chunk they caused the issue in doesn't display properly. Coincidentally, there's a sugarcane farm nearby that triggers sand falling updates, causing an error in that chunk, leading to a server crash and requiring a restart.

**Comment by killerprojecte** [comment] 2023-08-11 18:40
In my current tests, I found that some operations will cause problems when called in non-regional threads, such as stuck regional threads, etc.

**Comment by killerprojecte** [comment] 2023-08-11 18:41
I don't have any feasible solution to this problem at present, I can only wait for the plugin author to be compatible

**Comment by killerprojecte** [comment] 2023-08-11 18:44
I don't think DirtyFolia should be used in an environment with intensive operations on blocks The unstable behavior of the project itself will cause many errors

**Comment by IamRymatics** [comment] 2023-08-20 05:16
Save New Duplicate & Edit Just Text Discord
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
[12:03:49] [Region Scheduler Thread #4/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #505 centered at chunk [58, -151] in world 'world' failed to tick:
java.lang.NullPointerException: Cannot read field "f" because "pos" is null
	at io.papermc.paper.util.CoordinateUtils.getChunkKey(CoordinateUtils.java:29) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.removeTicketAtLevel(ChunkHolderManager.java:686) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at net.minecraft.server.level.DistanceManager.removeTicket(DistanceManager.java:97) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.removeTicketAtLevel(ServerChunkCache.java:119) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:469) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1502) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:367) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:388) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-DirtyFolia-"c4d50b6"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:03:49] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[12:03:49] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[12:03:49] [Region shutdown thread/INFO]: Stopping server

**Comment by killerprojecte** [comment] 2023-08-23 00:00
@IamRymatics have you try test it in PaperMC#Folia?

**Comment by R00tB33rMan** [comment] 2023-08-25 05:25
The initially provided error was reproducible on my end as well, when attempting a production-Folia transition. Hopefully further information can be gathered regarding this issue; however, it does appear quite obscure and bizarre. No specific plugins indicated that they were of cause nor actions. Via the console, these issues just simply happened.

**Comment by killerprojecte** [comment] 2023-08-26 05:40
This issue has been open for a long time, when I want to get more information about it, there is no progress, no one responds Maybe people always think that things are caused by DirtyFolia, so I can't investigate the cause

**Comment by R00tB33rMan** [comment] 2023-08-26 06:06
> This issue has been open for a long time, when I want to get more information about it, there is no progress, no one responds Maybe people always think that things are caused by DirtyFolia, so I can't investigate the cause

All issues present could result from PlayerGuild, Guilds, & BetterTeams. All three resources utilize a synchronous teleportation event, which causes users to timeout and may then (later) cause crashes like these.

I'd like to assist with resolving this issue. Can we privately communicate via Discord?

**Comment by 347180440** [comment] 2023-08-26 07:37
It's very rare to see this block crash now, but I've only recently started to notice why the server is CPU100%, the reason is [memory leak] when the server has 20 people running 9GB after 1 hour, 22GB after 3 hours, in short, I can reach the maximum of 60GB that day. After reaching the ceiling, the server will appear CPU 100% within a few hours, the server will restart when the block crashes in normal times, it is difficult to notice the reason for releasing the memory itself, now it does not crash, but memory leaks, when the memory reaches the ceiling, the server players only 5 people hang up at night memory is still at the peak, will not be recovered. I don't know why but I'm thinking about testing and screening.

**Comment by killerprojecte** [comment] 2023-08-27 00:57
> > This issue has been open for a long time, when I want to get more information about it, there is no progress, no one responds Maybe people always think that things are caused by DirtyFolia, so I can't investigate the cause
> 
> All issues present could result from PlayerGuild, Guilds, & BetterTeams. All three resources utilize a synchronous teleportation event, which causes users to timeout and may then (later) cause crashes like these.
> 
> I'd like to assist with resolving this issue. Can we privately communicate via Discord?

Add my discord : unlimitedmc

**Closed as completed** 2023-09-20 14:34 UTC
